<!DOCTYPE html>
<html lang="en-US">
<!--********************************************-->
<!--*       Generated from PreTeXt source      *-->
<!--*                                          *-->
<!--*         https://pretextbook.org          *-->
<!--*                                          *-->
<!--********************************************-->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="robots" content="noindex, nofollow">
</head>
<body class="ignore-math">
<h4 class="heading"><span class="type">Paragraph</span></h4>
<p>It is important to note here the way in which <span class="process-math">\(f(y)\)</span> fails to be differentiable. In particular, <span class="process-math">\(f(y)\)</span> is differentiable for all <span class="process-math">\(y\neq 0\)</span> and <span class="process-math">\(\displaystyle \lim_{y \to 0^+}f'(y)\lim_{y \to 0^+}f'(y)=\infty\text{.}\)</span>  What is unknown then is whether it is the simple failure of the derivative exist that is the issue, or whether it is the unboundedness of the derivative that is the issue.  It turns out that the issue is, in fact, the latter.  We can prove that an initial value problem has a unique solution if we assume continuity of <span class="process-math">\(\vec{f}(t,\vec{x})\)</span> in both variables and boundedness of the partial derivative <span class="process-math">\(\vec{f}_x(t,\vec{x})\text{.}\)</span>  But we can do better!</p>
<span class="incontext"><a href="sec-existencethms.html#p-29" class="internal">in-context</a></span>
</body>
</html>
